#!/usr/bin/env python3
"""Headless smoke matrix for G8 evidence — writes markdown report."""
from __future__ import annotations

import os
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs" / "GOAL_G8_SMOKE_EVIDENCE.md"
INTERACT_REPORT = ROOT / "docs" / "GOAL_G8_INTERACT_ACTIVATE_EVIDENCE.md"

AREA_SCENES = sorted(
	f"res://scenes/areas/{p.name}/{p.name}.tscn"
	for p in (ROOT / "scenes/areas").iterdir()
	if p.is_dir() and (p / f"{p.name}.tscn").exists()
)
INTERIOR_SCENES = sorted(
	f"res://scenes/interiors/{p.name}/{p.name}.tscn"
	for p in (ROOT / "scenes/interiors").iterdir()
	if p.is_dir() and (p / f"{p.name}.tscn").exists()
)
# Full outdoor shell + all interiors (load smoke).
SCENES = AREA_SCENES + INTERIOR_SCENES


def find_godot() -> str:
	# Prefer running process path (Windows).
	try:
		ps = subprocess.run(
			[
				"powershell",
				"-NoProfile",
				"-Command",
				"Get-Process | Where-Object { $_.ProcessName -match 'Godot' } | Select-Object -First 1 -ExpandProperty Path",
			],
			capture_output=True,
			text=True,
			check=False,
		)
		path = (ps.stdout or "").strip()
		if path and Path(path).exists():
			return path
	except OSError:
		pass
	env = Path(os.environ.get("GODOT", "") or os.environ.get("GODOT_PATH", ""))
	if env and env.exists():
		return str(env)
	raise SystemExit("Godot process not found — open the editor once, then re-run.")


def smoke(godot: str, scene: str) -> tuple[int, int]:
	log = Path(f"{Path.home()}/AppData/Local/Temp/dream_smoke_{scene.split('/')[-1]}.log")
	err = log.with_suffix(".err")
	proc = subprocess.run(
		[godot, "--path", str(ROOT), "--headless", "--quit-after", "2", scene],
		capture_output=True,
		timeout=90,
		check=False,
	)
	out = (proc.stdout or b"").decode("utf-8", errors="replace") + "\n" + (proc.stderr or b"").decode(
		"utf-8", errors="replace"
	)
	log.write_text(out, encoding="utf-8", errors="replace")
	err.write_text((proc.stderr or b"").decode("utf-8", errors="replace"), encoding="utf-8", errors="replace")
	errors = sum(1 for line in out.splitlines() if "ERROR:" in line)
	scripts = sum(
		1
		for line in out.splitlines()
		if "SCRIPT ERROR" in line or "Parse Error" in line
	)
	return errors, scripts


def smoke_interact_activate(godot: str) -> tuple[bool, str]:
	proc = subprocess.run(
		[
			godot,
			"--path",
			str(ROOT),
			"--headless",
			"-s",
			"res://tools/g8_interact_activate_smoke.gd",
		],
		capture_output=True,
		timeout=120,
		check=False,
	)
	out = (proc.stdout or b"").decode("utf-8", errors="replace") + "\n" + (proc.stderr or b"").decode(
		"utf-8", errors="replace"
	)
	log = Path.home() / "AppData/Local/Temp/dream_g8_interact_activate.log"
	log.write_text(out, encoding="utf-8", errors="replace")
	ok = "G8_INTERACT_SMOKE: PASS" in out and proc.returncode == 0
	lines = [
		"# Goal G8 interact-activate evidence",
		"",
		"**Runner:** `tools/g8_interact_activate_smoke.gd`",
		f"**Result:** {'PASS' if ok else 'FAIL'} (exit={proc.returncode})",
		"",
		"## Log excerpt",
		"",
		"```",
	]
	for line in out.splitlines():
		if "G8_INTERACT_SMOKE" in line or "SCRIPT ERROR" in line or "ERROR:" in line:
			lines.append(line)
	lines.extend(["```", "", "User Godot QA still required for visual fidelity.", ""])
	INTERACT_REPORT.write_text("\n".join(lines), encoding="utf-8")
	print("wrote", INTERACT_REPORT.relative_to(ROOT), "PASS" if ok else "FAIL")
	return ok, out


def main() -> int:
	godot = find_godot()
	print(f"scenes={len(SCENES)} (areas={len(AREA_SCENES)} interiors={len(INTERIOR_SCENES)})")
	rows: list[tuple[str, int, int, str]] = []
	for scene in SCENES:
		sid = scene.rsplit("/", 1)[-1].replace(".tscn", "")
		try:
			e, s = smoke(godot, scene)
			status = "PASS" if e == 0 and s == 0 else "FAIL"
		except Exception as exc:  # noqa: BLE001
			e, s, status = -1, -1, f"FAIL ({exc})"
		rows.append((sid, e, s, status))
		print(f"{sid}: ERRORS={e} SCRIPT={s} {status}")
		time.sleep(0.15)

	passed = sum(1 for *_, st in rows if st == "PASS")
	interact_ok, _ = smoke_interact_activate(godot)
	lines = [
		"# Goal G8 smoke evidence",
		"",
		f"**Date:** auto-generated by `tools/run_g8_smoke_matrix.py`",
		f"**Result:** {passed}/{len(rows)} scenes PASS (ERROR=0, SCRIPT=0)",
		f"**Interact activate:** {'PASS' if interact_ok else 'FAIL'} — see `GOAL_G8_INTERACT_ACTIVATE_EVIDENCE.md`",
		"",
		"| Scene | ERRORS | SCRIPT | Status |",
		"| --- | ---: | ---: | --- |",
	]
	for sid, e, s, st in rows:
		lines.append(f"| `{sid}` | {e} | {s} | {st} |")
	lines.extend(
		[
			"",
			"## Notes",
			"",
			"- Headless `--quit-after 2` load smoke (not full playthrough).",
			"- Interact-activate script fires C58 `activated` on square kit.",
			"- User local Godot QA still required for click/animation fidelity.",
			"- tomyud1 MCP screenshot path optional when server is up.",
			"",
		]
	)
	REPORT.write_text("\n".join(lines), encoding="utf-8")
	print("wrote", REPORT.relative_to(ROOT))
	return 0 if passed == len(rows) and interact_ok else 1


if __name__ == "__main__":
	sys.exit(main())
