#!/usr/bin/env python3
"""Headless smoke matrix for G8 evidence — writes markdown report."""
from __future__ import annotations

import os
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs" / "GOAL_G8_SMOKE_EVIDENCE.md"

SCENES = [
	"res://scenes/areas/village_square/village_square.tscn",
	"res://scenes/areas/market_street/market_street.tscn",
	"res://scenes/areas/farmland/farmland.tscn",
	"res://scenes/areas/farm_residential/farm_residential.tscn",
	"res://scenes/areas/forest_deep/forest_deep.tscn",
	"res://scenes/areas/forest_entrance/forest_entrance.tscn",
	"res://scenes/areas/river/river.tscn",
	"res://scenes/areas/lake/lake.tscn",
	"res://scenes/areas/lake_house/lake_house.tscn",
	"res://scenes/areas/station/station.tscn",
	"res://scenes/areas/waterfall/waterfall.tscn",
	"res://scenes/areas/lighthouse/lighthouse.tscn",
	"res://scenes/areas/hill_farm/hill_farm.tscn",
	"res://scenes/areas/village_residential/village_residential.tscn",
	"res://scenes/interiors/c01_home/c01_home.tscn",
	"res://scenes/interiors/c04_smith/c04_smith.tscn",
	"res://scenes/interiors/c06_town_hall/c06_town_hall.tscn",
	"res://scenes/interiors/c11_station/c11_station.tscn",
	"res://scenes/interiors/c40_museum/c40_museum.tscn",
	"res://scenes/interiors/c43_bathhouse/c43_bathhouse.tscn",
]


def find_godot() -> str:
	# Prefer running process path (Windows).
	try:
		ps = subprocess.run(
			[
				"powershell",
				"-NoProfile",
				"-Command",
				"Get-Process | Where-Object { $_.ProcessName -match 'Godot' } | Select-Object -First 1 -ExpandProperty Path",
			],
			capture_output=True,
			text=True,
			check=False,
		)
		path = (ps.stdout or "").strip()
		if path and Path(path).exists():
			return path
	except OSError:
		pass
	env = Path(os.environ.get("GODOT", "") or os.environ.get("GODOT_PATH", ""))
	if env and env.exists():
		return str(env)
	raise SystemExit("Godot process not found — open the editor once, then re-run.")


def smoke(godot: str, scene: str) -> tuple[int, int]:
	log = Path(f"{Path.home()}/AppData/Local/Temp/dream_smoke_{scene.split('/')[-1]}.log")
	err = log.with_suffix(".err")
	proc = subprocess.run(
		[godot, "--path", str(ROOT), "--headless", "--quit-after", "2", scene],
		capture_output=True,
		timeout=90,
		check=False,
	)
	out = (proc.stdout or b"").decode("utf-8", errors="replace") + "\n" + (proc.stderr or b"").decode(
		"utf-8", errors="replace"
	)
	log.write_text(out, encoding="utf-8", errors="replace")
	err.write_text((proc.stderr or b"").decode("utf-8", errors="replace"), encoding="utf-8", errors="replace")
	errors = sum(1 for line in out.splitlines() if "ERROR:" in line)
	scripts = sum(
		1
		for line in out.splitlines()
		if "SCRIPT ERROR" in line or "Parse Error" in line
	)
	return errors, scripts


def main() -> int:
	godot = find_godot()
	rows: list[tuple[str, int, int, str]] = []
	for scene in SCENES:
		sid = scene.rsplit("/", 1)[-1].replace(".tscn", "")
		try:
			e, s = smoke(godot, scene)
			status = "PASS" if e == 0 and s == 0 else "FAIL"
		except Exception as exc:  # noqa: BLE001
			e, s, status = -1, -1, f"FAIL ({exc})"
		rows.append((sid, e, s, status))
		print(f"{sid}: ERRORS={e} SCRIPT={s} {status}")
		time.sleep(0.2)

	passed = sum(1 for *_, st in rows if st == "PASS")
	lines = [
		"# Goal G8 smoke evidence",
		"",
		f"**Date:** auto-generated by `tools/run_g8_smoke_matrix.py`",
		f"**Result:** {passed}/{len(rows)} scenes PASS (ERROR=0, SCRIPT=0)",
		"",
		"| Scene | ERRORS | SCRIPT | Status |",
		"| --- | ---: | ---: | --- |",
	]
	for sid, e, s, st in rows:
		lines.append(f"| `{sid}` | {e} | {s} | {st} |")
	lines.extend(
		[
			"",
			"## Notes",
			"",
			"- Headless `--quit-after 2` load smoke (not full playthrough).",
			"- User local Godot QA still required for click/animation fidelity.",
			"- tomyud1 MCP screenshot path optional when server is up.",
			"",
		]
	)
	REPORT.write_text("\n".join(lines), encoding="utf-8")
	print("wrote", REPORT.relative_to(ROOT))
	return 0 if passed == len(rows) else 1


if __name__ == "__main__":
	sys.exit(main())
