#!/usr/bin/env python3
"""Slice painted interior furniture atlases + cozy wall strips into shippable PNGs.

Also builds an indoor table by stripping grass from outdoor bench_0.
Replaces PIL placeholder props. See INTERIOR_DIAGNOSIS.md.
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
PROP_OUT = ROOT / "assets" / "sprites" / "interior" / "props"
TILE_OUT = ROOT / "assets" / "sprites" / "interior" / "tiles"
ATLAS_DIR = ROOT / "assets" / "sprites" / "interior" / "_source_atlases"
DIAG = ROOT / "assets" / "sprites" / "interior" / "_diag"

# Generated by Cursor GenerateImage (copied in by this script if present).
HOME_SRC_CANDIDATES = [
    Path(r"C:\Users\孤白赟悫\.cursor\projects\d-GoDot-Projects-Dream\assets\interior_furniture_home_atlas.png"),
    ATLAS_DIR / "interior_furniture_home_atlas.png",
]
WORK_SRC_CANDIDATES = [
    Path(r"C:\Users\孤白赟悫\.cursor\projects\d-GoDot-Projects-Dream\assets\interior_furniture_work_atlas.png"),
    ATLAS_DIR / "interior_furniture_work_atlas.png",
]
COZY = ROOT / "assets" / "sprites" / "interior" / "c01_room_reference_cozy.png"
BENCH = ROOT / "assets" / "sprites" / "props" / "bench_0.png"

BLACK_T = 28
PAD = 2

# Reading order (top→bottom, left→right clusters) for home atlas — verified against generated sheet.
HOME_NAMES = [
    "fireplace_00",
    "stove_00",
    "bed_double_00",
    "bed_single_00",
    "dresser_00",
    "table_round_00",
    "stool_00",
    "stool_01",
    "rocking_00",
    "shelf_00",  # pantry
    "herbs_00",
]

# Work atlas reading order.
WORK_NAMES = [
    "forge_00",
    "anvil_00",
    "tool_rack_00",
    "counter_00",  # workbench / shop counter
    "bar_00",
    "shelf_shop_00",
    "basket_00",
    "notice_00",
    "table_pub_00",
    "stool_bar_00",
    "mug_shelf_00",
    "hay_00",
    "nest_00",
    "trough_00",
    "ledger_00",
    "coin_chest_00",
    "medicine_00",
    "roost_00",
]


def find_src(cands: list[Path]) -> Path:
    for p in cands:
        if p.exists():
            return p
    raise FileNotFoundError(cands)


def components(mask: np.ndarray) -> list[tuple[int, int, int, int]]:
    """Return bounding boxes (x0,y0,x1,y1) of 4-connected True islands, sorted TL."""
    h, w = mask.shape
    visited = np.zeros_like(mask, dtype=bool)
    boxes: list[tuple[int, int, int, int]] = []
    for y in range(h):
        for x in range(w):
            if not mask[y, x] or visited[y, x]:
                continue
            stack = [(y, x)]
            visited[y, x] = True
            ys, xs = [y], [x]
            while stack:
                cy, cx = stack.pop()
                for ny, nx in ((cy - 1, cx), (cy + 1, cx), (cy, cx - 1), (cy, cx + 1)):
                    if 0 <= ny < h and 0 <= nx < w and mask[ny, nx] and not visited[ny, nx]:
                        visited[ny, nx] = True
                        stack.append((ny, nx))
                        ys.append(ny)
                        xs.append(nx)
            y0, y1 = min(ys), max(ys)
            x0, x1 = min(xs), max(xs)
            area = (y1 - y0 + 1) * (x1 - x0 + 1)
            if area < 80:
                continue
            boxes.append((x0, y0, x1, y1))
    boxes.sort(key=lambda b: (b[1] // 80, b[0]))  # row bands then x
    return boxes


def slice_atlas(src: Path, names: list[str], out_dir: Path) -> list[str]:
    im = Image.open(src).convert("RGBA")
    a = np.array(im)
    rgb = a[:, :, :3]
    mask = ~((rgb[:, :, 0] < BLACK_T) & (rgb[:, :, 1] < BLACK_T) & (rgb[:, :, 2] < BLACK_T))
    boxes = components(mask)
    print(f"{src.name}: {len(boxes)} islands, {len(names)} names")
    written: list[str] = []
    for i, box in enumerate(boxes):
        x0, y0, x1, y1 = box
        x0 = max(0, x0 - PAD)
        y0 = max(0, y0 - PAD)
        x1 = min(im.width - 1, x1 + PAD)
        y1 = min(im.height - 1, y1 + PAD)
        crop = im.crop((x0, y0, x1 + 1, y1 + 1))
        # punch black to alpha
        ca = np.array(crop)
        m = (ca[:, :, 0] < BLACK_T) & (ca[:, :, 1] < BLACK_T) & (ca[:, :, 2] < BLACK_T)
        ca[m, 3] = 0
        crop = Image.fromarray(ca, "RGBA")
        name = names[i] if i < len(names) else f"extra_{i:02d}"
        path = out_dir / f"{name}.png"
        crop.save(path)
        written.append(name)
        print(f"  {name} {crop.size}")
    return written


def indoor_table_from_bench() -> None:
    """Strip bright grass from outdoor bench → indoor table+chair."""
    if not BENCH.exists():
        return
    im = Image.open(BENCH).convert("RGBA")
    a = np.array(im)
    r, g, b, al = a[:, :, 0], a[:, :, 1], a[:, :, 2], a[:, :, 3]
    grass = (g > 90) & (g > r + 25) & (g > b + 15) & (al > 200)
    a[grass, 3] = 0
    # trim
    ys, xs = np.where(a[:, :, 3] > 20)
    if len(xs) == 0:
        return
    crop = Image.fromarray(a, "RGBA").crop((xs.min(), ys.min(), xs.max() + 1, ys.max() + 1))
    out = PROP_OUT / "table_indoor_00.png"
    crop.save(out)
    print("wrote", out.name, crop.size)


def slice_cozy_walls() -> None:
    """Extract north-wall style tiles from cozy reference composite row."""
    if not COZY.exists():
        print("no cozy reference")
        return
    im = Image.open(COZY).convert("RGBA")
    # Row 4 composite walls ~ y357-458 from earlier band detect (index 3 in bands list was 357)
    # Use DIAG row_3 if present else crop
    row_path = DIAG / "row_3.png"
    if row_path.exists():
        row = Image.open(row_path).convert("RGBA")
    else:
        row = im.crop((0, 357, 1024, 459))
    a = np.array(row)
    # drop near-black / label dark bg
    rgb = a[:, :, :3]
    content = ~((rgb[:, :, 0] < 20) & (rgb[:, :, 1] < 20) & (rgb[:, :, 2] < 20))
    ys = np.where(content.any(axis=1))[0]
    xs = np.where(content.any(axis=0))[0]
    if len(ys) == 0:
        return
    row = row.crop((int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1))
    # skip label text strip if top ~12px is mostly dark/brown with high variance in x for letters
    # Resize height to 64 (upper 32 cream + lower 32 wainscot language)
    tw, th = row.size
    target_h = 64
    scale = target_h / th
    row = row.resize((max(32, int(tw * scale)), target_h), Image.Resampling.NEAREST)
    # cut 32-wide tiles
    n = max(1, row.width // 32)
    for i in range(min(n, 8)):
        tile = row.crop((i * 32, 0, (i + 1) * 32, 64))
        # split upper/lower for existing craft API
        upper = tile.crop((0, 0, 32, 32))
        lower = tile.crop((0, 32, 32, 64))
        upper.save(TILE_OUT / f"wall_upper_{i:02d}.png")
        lower.save(TILE_OUT / f"wall_lower_{i:02d}.png")
        tile.save(TILE_OUT / f"wall_full_{i:02d}.png")
        print(f"wall tile {i} {tile.size}")

    # window row (row_5)
    win_path = DIAG / "row_5.png"
    if win_path.exists():
        win = Image.open(win_path).convert("RGBA")
        wa = np.array(win)
        rgb = wa[:, :, :3]
        content = ~((rgb[:, :, 0] < 20) & (rgb[:, :, 1] < 20) & (rgb[:, :, 2] < 20))
        ys = np.where(content.any(axis=1))[0]
        xs = np.where(content.any(axis=0))[0]
        win = win.crop((int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1))
        # find glowing window segment: high yellow in center
        # take second quarter of strip as window
        w = win.width
        seg = win.crop((w // 4, 0, w // 2, win.height))
        seg = seg.resize((48, 64), Image.Resampling.NEAREST)
        # punch near-black
        sa = np.array(seg)
        m = (sa[:, :, 0] < 18) & (sa[:, :, 1] < 18) & (sa[:, :, 2] < 18)
        sa[m, 3] = 0
        Image.fromarray(sa, "RGBA").save(TILE_OUT / "window_00.png")
        print("window_00", seg.size)

    # rug from later rows if exist
    for name, idx in [("rug_strip", 6)]:
        rp = DIAG / f"row_{idx}.png"
        if not rp.exists():
            continue
        rug = Image.open(rp).convert("RGBA")
        ra = np.array(rug)
        content = ~((ra[:, :, 0] < 20) & (ra[:, :, 1] < 20) & (ra[:, :, 2] < 20))
        ys = np.where(content.any(axis=1))[0]
        xs = np.where(content.any(axis=0))[0]
        rug = rug.crop((int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1))
        # 2x2 quarters at 32
        rug = rug.resize((64, 64), Image.Resampling.NEAREST)
        for qy in range(2):
            for qx in range(2):
                q = rug.crop((qx * 32, qy * 32, (qx + 1) * 32, (qy + 1) * 32))
                q.save(TILE_OUT / f"rug_{qy}_{qx}.png")
        print("rugs refreshed from cozy")


def main() -> None:
    PROP_OUT.mkdir(parents=True, exist_ok=True)
    TILE_OUT.mkdir(parents=True, exist_ok=True)
    ATLAS_DIR.mkdir(parents=True, exist_ok=True)

    home = find_src(HOME_SRC_CANDIDATES)
    work = find_src(WORK_SRC_CANDIDATES)
    shutil.copy2(home, ATLAS_DIR / "interior_furniture_home_atlas.png")
    shutil.copy2(work, ATLAS_DIR / "interior_furniture_work_atlas.png")

    # Archive old PIL placeholders
    archive = PROP_OUT / "_pil_archive"
    archive.mkdir(exist_ok=True)
    for p in list(PROP_OUT.glob("*.png")):
        if p.stat().st_size < 800:  # tiny PIL files
            shutil.move(str(p), archive / p.name)

    h_names = slice_atlas(home, HOME_NAMES, PROP_OUT)
    w_names = slice_atlas(work, WORK_NAMES, PROP_OUT)
    indoor_table_from_bench()
    slice_cozy_walls()

    # Aliases expected by profiles
    aliases = {
        "shelf_shop_00.png": "shelf_00.png",  # keep pantry if shop missing overwrite carefully
        "table_pub_00.png": "table_round_00.png",
        "stool_bar_00.png": "stool_00.png",
        "stool_01.png": "stool_00.png",
    }
    # Don't overwrite home shelf with shop — copy shop to shelf_grocery
    shop = PROP_OUT / "shelf_shop_00.png"
    if shop.exists():
        shutil.copy2(shop, PROP_OUT / "shelf_grocery_00.png")
    pub = PROP_OUT / "table_pub_00.png"
    if pub.exists() and not (PROP_OUT / "table_round_00.png").exists():
        shutil.copy2(pub, PROP_OUT / "table_round_00.png")
    # Prefer indoor table for dining when present
    ti = PROP_OUT / "table_indoor_00.png"
    if ti.exists():
        shutil.copy2(ti, PROP_OUT / "table_dining_00.png")

    meta = {"home": h_names, "work": w_names}
    (ATLAS_DIR / "slice_manifest.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    print("done")


if __name__ == "__main__":
    main()
